# Generated by Django 2.1.15 on 2024-03-31 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20240330_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='State',
            new_name='state',
        ),
    ]
